#!/bin/bash

if [[ $# -gt 0 ]] ; then
    echo 'Usage: $ ./03' >&2; exit 1
fi

echo -e "What's your age?"

read age

re='^[0-9]+$'

if ! [[ $age =~ $re ]]; then
  echo "Your answer is not a number" >&2; exit 1
fi

if [ "$age" -ge 18 ]; then
  echo "You are allowed to drink"
else
  echo "You are not allowed to drink yet!"
fi 
